version: '3.8'

services:
  web:
    # Собираем образ из текущей папки (ищет Dockerfile)
    build: .
    
    # Команда, которая запустится внутри контейнера
    command: python manage.py runserver 0.0.0.0:8000
    
    # Пробрасываем порты: [порт на компе]:[порт в контейнере]
    ports:
      - "8000:8000"
    
    # Монтируем папку с кодом внутрь контейнера
    # Это позволит коду обновляться "на лету" без пересборки образа
    volumes:
      - .:/app
    
    # Переменные окружения (например, чтобы логи Django сразу летели в консоль)
    environment:
      - PYTHONUNBUFFERED=1